make:
	javac -d bin src/Image.java
	java -cp bin src.FinalImages

second Part:
	javac -d bin src/SortImages.java #because this needs to be from root to see package and get FinalImages class
	java -cp bin src.SortImages

makeAllInSRC:
	javac -d Image.java #since in package src it compiles to src.Image
	java -cp ../ src.FinalImages #from src folder
	#java src.FinalImages #from root folder you can just do
	#java FinalImages from src DOES NOT WORK




secondPart:
	javac SortImages.java -d ../bin
	java -cp ../bin SortImages


#from root
#javac -d ../bin trial.java
#java -cp ../bin src.trial
