make:
	javac Image.java -d ../bin
	#java -cp ../bin Image
	java -cp ../bin FinalImages

secondPart:
	javac SortImages.java -d ../bin
	java -cp ../bin SortImages

old:
	javac Grayscale.java
	java Grayscale
